export const ENDPOINT_MAIN_REG = '/api/users/auth/signup'
export const ENDPOINT_MAIN_AUTH = '/api/users/auth/signin'
export const ENDPOINT_USER_UPDATE = ''
export const ENDPOINT_ALL_SERVICES = '/api/services'
export const ENDPOINT_ALL_MASTERS = '/api/users/masters'
export const ENDPOINT_ORDERS = '/api/orders'